[package]
name = "cache-rs"
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]

[dependencies]
regex = "*"
log = "*"
log4rs = "*"
time = "*"
clap = "*"
fnv = "*"
ansi_term = "*"
lazy_static = "*"
parking_lot = "*"
chan-signal = "*"
postgres = "*"
daemonize = "*"
