[package]
name = "cache-rs"
version = "1.0.4"
authors = ["Georg Brandl <georg@python.org>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
log = "*"
time = "*"
libc = "*"
fxhash = "*"
mlzlog = "*"
regex = "*"
memchr = "*"
mlzutil = "*"
structopt = "*"
aho-corasick = "*"
signal-hook = "*"
lazy_static = "*"
parking_lot = "*"
daemonize = "*"
crossbeam-channel = "*"
postgres = { version = "*", optional = true }
