[package]
name = "cache-rs"
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]

[dependencies]
regex = "*"
log = "*"
log4rs = "*"
odds = "*"
time = "*"
docopt = "*"
ansi_term = "*"
lazy_static = "*"
rustc-serialize = "*"
chan-signal = "*"
postgres = "*"
daemonize = "*"
