[package]
name = "cache-rs"
version = "0.1.0"
authors = ["Georg Brandl <georg@python.org>"]

[dependencies]
log = "*"
time = "*"
fnv = "*"
mlzlog = "*"
regex = "*"
clap = "*"
lazy_static = "*"
parking_lot = "*"
chan-signal = "*"
postgres = "*"
daemonize = "*"
