[package]
name = "cache-rs"
version = "1.0.4"
authors = ["Georg Brandl <georg@python.org>"]

[profile.release]
lto = true

[dependencies]
log = "*"
time = "*"
fnv = "*"
mlzlog = "*"
regex = "*"
memchr = "*"
mlzutil = "*"
structopt = "*"
aho-corasick = "*"
lazy_static = "*"
parking_lot = "*"
chan-signal = "*"
daemonize = "*"
crossbeam-channel = "*"
postgres = { version = "*", optional = true }
