[package]
name = "cache-rs"
version = "1.0.3"
authors = ["Georg Brandl <georg@python.org>"]

[profile.release]
lto = true

[dependencies]
log = "*"
time = "*"
fnv = "*"
mlzlog = "*"
regex = "*"
clap = "*"
lazy_static = "*"
parking_lot = "*"
chan-signal = "*"
daemonize = "*"
postgres = { version = "*", optional = true }
